<div class="page-heading"><div><span class="kicker">SYSTEM CONTROL</span><h1>Settings</h1><p>Configure alert delivery, ingestion behaviour and the private scan boundary.</p></div><span class="panel-badge">SECRETS STAY IN .ENV</span></div>
<form method="post" action="<?= e(url('settings-save')) ?>" class="settings-grid"><?= Csrf::field() ?>
    <section class="panel"><div class="panel-heading"><div><span class="kicker">GENERAL</span><h2>System identity</h2></div></div><div class="stacked-form settings-form"><label>Display name<input type="text" name="display_name" value="<?= e($settings['display_name']) ?>" maxlength="100" required></label><label>System timezone<select name="system_timezone"><?php foreach (['Asia/Kuala_Lumpur','UTC','Asia/Singapore','Australia/Perth'] as $zone): ?><option<?= selected($settings['system_timezone'], $zone) ?>><?= e($zone) ?></option><?php endforeach; ?></select></label><label>Deduplication window (minutes)<input type="number" name="dedupe_window_minutes" value="<?= (int) $settings['dedupe_window_minutes'] ?>" min="1" max="1440" required><small>The Python worker groups matching fingerprints inside this window.</small></label></div></section>
    <section class="panel"><div class="panel-heading"><div><span class="kicker">TELEGRAM</span><h2>Alert delivery</h2></div><span class="secret-state <?= config('telegram.token') !== '' ? 'configured' : '' ?>"><?= config('telegram.token') !== '' ? 'Token configured' : 'Token missing' ?></span></div><div class="stacked-form settings-form"><label class="switch-row"><span><strong>Enable Telegram alerts</strong><small>New incidents at or above the threshold</small></span><input type="checkbox" name="telegram_enabled" value="1"<?= checked($settings['telegram_enabled'] === '1') ?>></label><label>Telegram chat ID<input type="text" name="telegram_chat_id" value="<?= e($settings['telegram_chat_id']) ?>" maxlength="80" placeholder="-1001234567890"></label><label>Minimum alert severity<select name="alert_min_severity"><?php foreach (['Low','Medium','High','Critical'] as $severity): ?><option<?= selected($settings['alert_min_severity'], $severity) ?>><?= e($severity) ?></option><?php endforeach; ?></select></label><p class="safety-copy">The bot token is read only from <code>TELEGRAM_BOT_TOKEN</code> in <code>.env</code>.</p><button class="button button-secondary" type="submit" formaction="<?= e(url('telegram-test')) ?>">Send test alert</button></div></section>
    <section class="panel settings-full database-guide"><div class="panel-heading"><div><span class="kicker">SQLITE DATABASE</span><h2>Open in HeidiSQL</h2></div><span class="secret-state configured">Local file</span></div><div class="database-guide-body"><div><p>The database is a single SQLite file for Laragon and HeidiSQL. Imported incidents appear here when the worker runs.</p><code class="database-path" id="database-path"><?= e((string) config('db.path')) ?></code></div><div class="database-steps"><span><b>1</b> Double-click <code>database\Open in HeidiSQL.bat</code></span><span><b>2</b> Or create a HeidiSQL session with network type <strong>SQLite</strong></span><span><b>3</b> Select the file path shown here</span></div><button class="button button-secondary" type="button" data-copy-target="database-path">Copy database path</button></div></section>
    <section class="panel settings-full"><div class="panel-heading"><div><span class="kicker">SCAN BOUNDARY</span><h2>Authorised private lab CIDRs</h2></div></div><div class="stacked-form settings-form"><label>One RFC1918 CIDR per line<textarea name="nmap_allowed_cidrs" rows="5" spellcheck="false" required><?= e($settings['nmap_allowed_cidrs']) ?></textarea><small>Examples: 192.168.56.0/24 and 10.10.10.0/24. Public targets remain blocked even if entered here.</small></label></div></section>
    <div class="settings-actions"><button class="button button-primary" type="submit">Save system settings</button></div>
</form>
<form method="post" action="<?= e(url('wazuh-test')) ?>" class="settings-grid wazuh-integration">
    <?= Csrf::field() ?>
    <section class="panel settings-full">
        <div class="panel-heading"><div><span class="kicker">WAZUH INTEGRATION</span><h2>Manager API connection</h2></div><span class="secret-state <?= $wazuhStatus === 'Connected' ? 'configured' : '' ?>" role="status"><?= e($wazuhStatus) ?></span></div>
        <div class="stacked-form settings-form">
            <p class="safety-copy">Test authentication from the Watch-U server. Credentials stay in <code>.env</code>; this test does not import alerts.</p>
            <button class="button button-secondary" type="submit">Test Connection</button>
        </div>
    </section>
</form>
